/*******************************************************************************
 *    Copyright 2015 Dorian Perkins, Younghwan Go, Nitin Agrawal, Akshat Aranya
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/
package com.necla.simba.protocol;
// Generated by proto2javame, Sun Feb 08 14:12:26 KST 2015.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class ObjectHeader extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String column;
	private static final int fieldNumberColumn = 1;

	private final int oid;
	private static final int fieldNumberOid = 2;

	private final int num_chunks;
	private static final int fieldNumberNum_chunks = 3;
	private final boolean hasNum_chunks;


	public static Builder newBuilder() {
		return new Builder();
	}

	private ObjectHeader(final Builder builder) {
		if (builder.hasColumn && builder.hasOid ) {
			this.column = builder.column;
			this.oid = builder.oid;
			this.num_chunks = builder.num_chunks;
			this.hasNum_chunks = builder.hasNum_chunks;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				" column:" + builder.hasColumn + " oid:" + builder.hasOid + "");
		}
	}

	public static class Builder {
		private String column;
		private boolean hasColumn = false;

		private int oid;
		private boolean hasOid = false;

		private int num_chunks;
		private boolean hasNum_chunks = false;


		private Builder() {
		}

		public Builder setColumn(final String column) {
			this.column = column;
			this.hasColumn = true;
			return this;
		}

		public Builder setOid(final int oid) {
			this.oid = oid;
			this.hasOid = true;
			return this;
		}

		public Builder setNum_chunks(final int num_chunks) {
			this.num_chunks = num_chunks;
			this.hasNum_chunks = true;
			return this;
		}

		public ObjectHeader build() {
			return new ObjectHeader(this);
		}
	}

	public String getColumn() {
		return column;
	}

	public int getOid() {
		return oid;
	}

	public int getNum_chunks() {
		return num_chunks;
	}

	public boolean hasNum_chunks() {
		return hasNum_chunks;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "column = " + this.column + TAB;
		retValue += "oid = " + this.oid + TAB;
		if(hasNum_chunks) retValue += "num_chunks = " + this.num_chunks + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberColumn, column);
		totalSize += ComputeSizeUtil.computeIntSize(fieldNumberOid, oid);
		if(hasNum_chunks) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberNum_chunks, num_chunks);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeString(fieldNumberColumn, column);
		writer.writeInt(fieldNumberOid, oid);
		if(hasNum_chunks) writer.writeInt(fieldNumberNum_chunks, num_chunks);
	}

	static ObjectHeader parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final ObjectHeader.Builder builder = ObjectHeader.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberColumn:
				builder.setColumn(reader.readString(fieldNumber));
				break;
			case fieldNumberOid:
				builder.setOid(reader.readInt(fieldNumber));
				break;
			case fieldNumberNum_chunks:
				builder.setNum_chunks(reader.readInt(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		ObjectHeader.unknownTagHandler = unknownTagHandler;
	}

	public static ObjectHeader parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static ObjectHeader parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static ObjectHeader parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}