/*******************************************************************************
 *    Copyright 2015 Dorian Perkins, Younghwan Go, Nitin Agrawal, Akshat Aranya
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/
package com.necla.simba.protocol;
// Generated by proto2javame, Sun Feb 08 14:12:31 KST 2015.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class SimbaMultiMessage extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final java.util.Vector messages;
	private static final int fieldNumberMessages = 1;


	public static Builder newBuilder() {
		return new Builder();
	}

	private SimbaMultiMessage(final Builder builder) {
		if (true) {
			this.messages = builder.messages;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				"");
		}
	}

	public static class Builder {
		private java.util.Vector messages = new java.util.Vector();
		private boolean hasMessages = false;


		private Builder() {
		}

		public Builder setMessages(final java.util.Vector messages) {
			if(!hasMessages) {
				hasMessages = true;
			}
			this.messages = messages;
			return this;
		}


		public Builder addElementMessages(final SimbaMessage element) {
			if(!hasMessages) {
				hasMessages = true;
			}
			messages.addElement(element);
			return this;
		}

		public SimbaMultiMessage build() {
			return new SimbaMultiMessage(this);
		}
	}

	public java.util.Vector getMessages() {
		return messages;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "messages = " + this.messages + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberMessages, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, messages);

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeList(fieldNumberMessages, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, messages);
	}

	static SimbaMultiMessage parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final SimbaMultiMessage.Builder builder = SimbaMultiMessage.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberMessages:
				Vector vcMessages = reader.readMessages(fieldNumberMessages);
				for(int i = 0 ; i < vcMessages.size(); i++) {
					byte[] eachBinData = (byte[]) vcMessages.elementAt(i);
					SimbaMessage.Builder builderMessages = SimbaMessage.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolMessages = true;
					int nestedFieldMessages = -1;
					while(boolMessages) {
						nestedFieldMessages = getNextFieldNumber(innerInputReader);
						boolMessages = SimbaMessage.populateBuilderWithField(innerInputReader, builderMessages, nestedFieldMessages);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementMessages(builderMessages.build());
				}
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		SimbaMultiMessage.unknownTagHandler = unknownTagHandler;
	}

	public static SimbaMultiMessage parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static SimbaMultiMessage parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static SimbaMultiMessage parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}