/*******************************************************************************
 *    Copyright 2015 Dorian Perkins, Younghwan Go, Nitin Agrawal, Akshat Aranya
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/
package com.necla.simba.protocol;
// Generated by proto2javame, Sun Feb 08 14:12:26 KST 2015.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class SubscribeTable extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String app;
	private static final int fieldNumberApp = 1;

	private final String tbl;
	private static final int fieldNumberTbl = 2;

	private final int period;
	private static final int fieldNumberPeriod = 3;
	private final boolean hasPeriod;

	private final int delayTolerance;
	private static final int fieldNumberDelayTolerance = 4;
	private final boolean hasDelayTolerance;

	private final int rev;
	private static final int fieldNumberRev = 5;
	private final boolean hasRev;


	public static Builder newBuilder() {
		return new Builder();
	}

	private SubscribeTable(final Builder builder) {
		if (builder.hasApp && builder.hasTbl ) {
			this.app = builder.app;
			this.tbl = builder.tbl;
			this.period = builder.period;
			this.hasPeriod = builder.hasPeriod;
			this.delayTolerance = builder.delayTolerance;
			this.hasDelayTolerance = builder.hasDelayTolerance;
			this.rev = builder.rev;
			this.hasRev = builder.hasRev;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				" app:" + builder.hasApp + " tbl:" + builder.hasTbl + "");
		}
	}

	public static class Builder {
		private String app;
		private boolean hasApp = false;

		private String tbl;
		private boolean hasTbl = false;

		private int period;
		private boolean hasPeriod = false;

		private int delayTolerance;
		private boolean hasDelayTolerance = false;

		private int rev;
		private boolean hasRev = false;


		private Builder() {
		}

		public Builder setApp(final String app) {
			this.app = app;
			this.hasApp = true;
			return this;
		}

		public Builder setTbl(final String tbl) {
			this.tbl = tbl;
			this.hasTbl = true;
			return this;
		}

		public Builder setPeriod(final int period) {
			this.period = period;
			this.hasPeriod = true;
			return this;
		}

		public Builder setDelayTolerance(final int delayTolerance) {
			this.delayTolerance = delayTolerance;
			this.hasDelayTolerance = true;
			return this;
		}

		public Builder setRev(final int rev) {
			this.rev = rev;
			this.hasRev = true;
			return this;
		}

		public SubscribeTable build() {
			return new SubscribeTable(this);
		}
	}

	public String getApp() {
		return app;
	}

	public String getTbl() {
		return tbl;
	}

	public int getPeriod() {
		return period;
	}

	public boolean hasPeriod() {
		return hasPeriod;
	}

	public int getDelayTolerance() {
		return delayTolerance;
	}

	public boolean hasDelayTolerance() {
		return hasDelayTolerance;
	}

	public int getRev() {
		return rev;
	}

	public boolean hasRev() {
		return hasRev;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "app = " + this.app + TAB;
		retValue += "tbl = " + this.tbl + TAB;
		if(hasPeriod) retValue += "period = " + this.period + TAB;
		if(hasDelayTolerance) retValue += "delayTolerance = " + this.delayTolerance + TAB;
		if(hasRev) retValue += "rev = " + this.rev + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberApp, app);
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberTbl, tbl);
		if(hasPeriod) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberPeriod, period);
		if(hasDelayTolerance) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberDelayTolerance, delayTolerance);
		if(hasRev) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberRev, rev);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeString(fieldNumberApp, app);
		writer.writeString(fieldNumberTbl, tbl);
		if(hasPeriod) writer.writeInt(fieldNumberPeriod, period);
		if(hasDelayTolerance) writer.writeInt(fieldNumberDelayTolerance, delayTolerance);
		if(hasRev) writer.writeInt(fieldNumberRev, rev);
	}

	static SubscribeTable parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final SubscribeTable.Builder builder = SubscribeTable.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberApp:
				builder.setApp(reader.readString(fieldNumber));
				break;
			case fieldNumberTbl:
				builder.setTbl(reader.readString(fieldNumber));
				break;
			case fieldNumberPeriod:
				builder.setPeriod(reader.readInt(fieldNumber));
				break;
			case fieldNumberDelayTolerance:
				builder.setDelayTolerance(reader.readInt(fieldNumber));
				break;
			case fieldNumberRev:
				builder.setRev(reader.readInt(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		SubscribeTable.unknownTagHandler = unknownTagHandler;
	}

	public static SubscribeTable parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static SubscribeTable parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static SubscribeTable parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}