/*******************************************************************************
 *    Copyright 2015 Dorian Perkins, Younghwan Go, Nitin Agrawal, Akshat Aranya
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/
package com.necla.simba.protocol;
// Generated by proto2javame, Sun Feb 08 14:12:26 KST 2015.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class SyncHeader extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String app;
	private static final int fieldNumberApp = 1;

	private final String tbl;
	private static final int fieldNumberTbl = 2;

	private final java.util.Vector dirtyRows;
	private static final int fieldNumberDirtyRows = 3;

	private final java.util.Vector deletedRows;
	private static final int fieldNumberDeletedRows = 4;

	private final int trans_id;
	private static final int fieldNumberTrans_id = 5;


	public static Builder newBuilder() {
		return new Builder();
	}

	private SyncHeader(final Builder builder) {
		if (builder.hasApp && builder.hasTbl && builder.hasTrans_id ) {
			this.app = builder.app;
			this.tbl = builder.tbl;
			this.dirtyRows = builder.dirtyRows;
			this.deletedRows = builder.deletedRows;
			this.trans_id = builder.trans_id;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				" app:" + builder.hasApp + " tbl:" + builder.hasTbl + " trans_id:" + builder.hasTrans_id + "");
		}
	}

	public static class Builder {
		private String app;
		private boolean hasApp = false;

		private String tbl;
		private boolean hasTbl = false;

		private java.util.Vector dirtyRows = new java.util.Vector();
		private boolean hasDirtyRows = false;

		private java.util.Vector deletedRows = new java.util.Vector();
		private boolean hasDeletedRows = false;

		private int trans_id;
		private boolean hasTrans_id = false;


		private Builder() {
		}

		public Builder setApp(final String app) {
			this.app = app;
			this.hasApp = true;
			return this;
		}

		public Builder setTbl(final String tbl) {
			this.tbl = tbl;
			this.hasTbl = true;
			return this;
		}

		public Builder setDirtyRows(final java.util.Vector dirtyRows) {
			if(!hasDirtyRows) {
				hasDirtyRows = true;
			}
			this.dirtyRows = dirtyRows;
			return this;
		}


		public Builder addElementDirtyRows(final DataRow element) {
			if(!hasDirtyRows) {
				hasDirtyRows = true;
			}
			dirtyRows.addElement(element);
			return this;
		}

		public Builder setDeletedRows(final java.util.Vector deletedRows) {
			if(!hasDeletedRows) {
				hasDeletedRows = true;
			}
			this.deletedRows = deletedRows;
			return this;
		}


		public Builder addElementDeletedRows(final DataRow element) {
			if(!hasDeletedRows) {
				hasDeletedRows = true;
			}
			deletedRows.addElement(element);
			return this;
		}

		public Builder setTrans_id(final int trans_id) {
			this.trans_id = trans_id;
			this.hasTrans_id = true;
			return this;
		}

		public SyncHeader build() {
			return new SyncHeader(this);
		}
	}

	public String getApp() {
		return app;
	}

	public String getTbl() {
		return tbl;
	}

	public java.util.Vector getDirtyRows() {
		return dirtyRows;
	}

	public java.util.Vector getDeletedRows() {
		return deletedRows;
	}

	public int getTrans_id() {
		return trans_id;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "app = " + this.app + TAB;
		retValue += "tbl = " + this.tbl + TAB;
		retValue += "dirtyRows = " + this.dirtyRows + TAB;
		retValue += "deletedRows = " + this.deletedRows + TAB;
		retValue += "trans_id = " + this.trans_id + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberApp, app);
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberTbl, tbl);
		totalSize += ComputeSizeUtil.computeIntSize(fieldNumberTrans_id, trans_id);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberDirtyRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, dirtyRows);
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberDeletedRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, deletedRows);

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeString(fieldNumberApp, app);
		writer.writeString(fieldNumberTbl, tbl);
		writer.writeList(fieldNumberDirtyRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, dirtyRows);
		writer.writeList(fieldNumberDeletedRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, deletedRows);
		writer.writeInt(fieldNumberTrans_id, trans_id);
	}

	static SyncHeader parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final SyncHeader.Builder builder = SyncHeader.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberApp:
				builder.setApp(reader.readString(fieldNumber));
				break;
			case fieldNumberTbl:
				builder.setTbl(reader.readString(fieldNumber));
				break;
			case fieldNumberDirtyRows:
				Vector vcDirtyRows = reader.readMessages(fieldNumberDirtyRows);
				for(int i = 0 ; i < vcDirtyRows.size(); i++) {
					byte[] eachBinData = (byte[]) vcDirtyRows.elementAt(i);
					DataRow.Builder builderDirtyRows = DataRow.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolDirtyRows = true;
					int nestedFieldDirtyRows = -1;
					while(boolDirtyRows) {
						nestedFieldDirtyRows = getNextFieldNumber(innerInputReader);
						boolDirtyRows = DataRow.populateBuilderWithField(innerInputReader, builderDirtyRows, nestedFieldDirtyRows);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementDirtyRows(builderDirtyRows.build());
				}
				break;
			case fieldNumberDeletedRows:
				Vector vcDeletedRows = reader.readMessages(fieldNumberDeletedRows);
				for(int i = 0 ; i < vcDeletedRows.size(); i++) {
					byte[] eachBinData = (byte[]) vcDeletedRows.elementAt(i);
					DataRow.Builder builderDeletedRows = DataRow.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolDeletedRows = true;
					int nestedFieldDeletedRows = -1;
					while(boolDeletedRows) {
						nestedFieldDeletedRows = getNextFieldNumber(innerInputReader);
						boolDeletedRows = DataRow.populateBuilderWithField(innerInputReader, builderDeletedRows, nestedFieldDeletedRows);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementDeletedRows(builderDeletedRows.build());
				}
				break;
			case fieldNumberTrans_id:
				builder.setTrans_id(reader.readInt(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		SyncHeader.unknownTagHandler = unknownTagHandler;
	}

	public static SyncHeader parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static SyncHeader parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static SyncHeader parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}