/*******************************************************************************
 *    Copyright 2015 Dorian Perkins, Younghwan Go, Nitin Agrawal, Akshat Aranya
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/
package com.necla.simba.protocol;
// Generated by proto2javame, Sun Feb 08 14:12:26 KST 2015.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class SyncResponse extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String app;
	private static final int fieldNumberApp = 1;

	private final String tbl;
	private static final int fieldNumberTbl = 2;

	private final int result;
	private static final int fieldNumberResult = 3;

	private final int trans_id;
	private static final int fieldNumberTrans_id = 4;

	private final java.util.Vector syncedRows;
	private static final int fieldNumberSyncedRows = 5;

	private final java.util.Vector conflictedRows;
	private static final int fieldNumberConflictedRows = 6;


	public static Builder newBuilder() {
		return new Builder();
	}

	private SyncResponse(final Builder builder) {
		if (builder.hasApp && builder.hasTbl && builder.hasResult && builder.hasTrans_id ) {
			this.app = builder.app;
			this.tbl = builder.tbl;
			this.result = builder.result;
			this.trans_id = builder.trans_id;
			this.syncedRows = builder.syncedRows;
			this.conflictedRows = builder.conflictedRows;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				" app:" + builder.hasApp + " tbl:" + builder.hasTbl + " result:" + builder.hasResult + " trans_id:" + builder.hasTrans_id + "");
		}
	}

	public static class SyncResult {
		public static int OK = 1;
		public static int TABLE_NOT_FOUND = 2;

		public static String getStringValue(int value) {
			String retValue;

			switch(value) {
				case 1:
					retValue = "OK";
					break;
				case 2:
					retValue = "TABLE_NOT_FOUND";
					break;
				default:
					retValue = "";
					break;
			}

			return retValue;
		}
	}

	public static class Builder {
		private String app;
		private boolean hasApp = false;

		private String tbl;
		private boolean hasTbl = false;

		private int result;
		private boolean hasResult = false;

		private int trans_id;
		private boolean hasTrans_id = false;

		private java.util.Vector syncedRows = new java.util.Vector();
		private boolean hasSyncedRows = false;

		private java.util.Vector conflictedRows = new java.util.Vector();
		private boolean hasConflictedRows = false;


		private Builder() {
		}

		public Builder setApp(final String app) {
			this.app = app;
			this.hasApp = true;
			return this;
		}

		public Builder setTbl(final String tbl) {
			this.tbl = tbl;
			this.hasTbl = true;
			return this;
		}

		public Builder setResult(final int result) {
			this.result = result;
			this.hasResult = true;
			return this;
		}

		public Builder setTrans_id(final int trans_id) {
			this.trans_id = trans_id;
			this.hasTrans_id = true;
			return this;
		}

		public Builder setSyncedRows(final java.util.Vector syncedRows) {
			if(!hasSyncedRows) {
				hasSyncedRows = true;
			}
			this.syncedRows = syncedRows;
			return this;
		}


		public Builder addElementSyncedRows(final DataRow element) {
			if(!hasSyncedRows) {
				hasSyncedRows = true;
			}
			syncedRows.addElement(element);
			return this;
		}

		public Builder setConflictedRows(final java.util.Vector conflictedRows) {
			if(!hasConflictedRows) {
				hasConflictedRows = true;
			}
			this.conflictedRows = conflictedRows;
			return this;
		}


		public Builder addElementConflictedRows(final DataRow element) {
			if(!hasConflictedRows) {
				hasConflictedRows = true;
			}
			conflictedRows.addElement(element);
			return this;
		}

		public SyncResponse build() {
			return new SyncResponse(this);
		}
	}

	public String getApp() {
		return app;
	}

	public String getTbl() {
		return tbl;
	}

	public int getResult() {
		return result;
	}

	public int getTrans_id() {
		return trans_id;
	}

	public java.util.Vector getSyncedRows() {
		return syncedRows;
	}

	public java.util.Vector getConflictedRows() {
		return conflictedRows;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "app = " + this.app + TAB;
		retValue += "tbl = " + this.tbl + TAB;
		retValue += "result = " + this.result + TAB;
		retValue += "trans_id = " + this.trans_id + TAB;
		retValue += "syncedRows = " + this.syncedRows + TAB;
		retValue += "conflictedRows = " + this.conflictedRows + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberApp, app);
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberTbl, tbl);
		totalSize += ComputeSizeUtil.computeIntSize(fieldNumberResult, result);
		totalSize += ComputeSizeUtil.computeIntSize(fieldNumberTrans_id, trans_id);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberSyncedRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, syncedRows);
		messageSize += ComputeSizeUtil.computeListSize(fieldNumberConflictedRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, conflictedRows);

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeString(fieldNumberApp, app);
		writer.writeString(fieldNumberTbl, tbl);
		writer.writeInt(fieldNumberResult, result);
		writer.writeInt(fieldNumberTrans_id, trans_id);
		writer.writeList(fieldNumberSyncedRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, syncedRows);
		writer.writeList(fieldNumberConflictedRows, net.jarlehansen.protobuf.javame.SupportedDataTypes.DATA_TYPE_CUSTOM, conflictedRows);
	}

	static SyncResponse parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final SyncResponse.Builder builder = SyncResponse.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberApp:
				builder.setApp(reader.readString(fieldNumber));
				break;
			case fieldNumberTbl:
				builder.setTbl(reader.readString(fieldNumber));
				break;
			case fieldNumberResult:
				builder.setResult(reader.readInt(fieldNumber));
				break;
			case fieldNumberTrans_id:
				builder.setTrans_id(reader.readInt(fieldNumber));
				break;
			case fieldNumberSyncedRows:
				Vector vcSyncedRows = reader.readMessages(fieldNumberSyncedRows);
				for(int i = 0 ; i < vcSyncedRows.size(); i++) {
					byte[] eachBinData = (byte[]) vcSyncedRows.elementAt(i);
					DataRow.Builder builderSyncedRows = DataRow.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolSyncedRows = true;
					int nestedFieldSyncedRows = -1;
					while(boolSyncedRows) {
						nestedFieldSyncedRows = getNextFieldNumber(innerInputReader);
						boolSyncedRows = DataRow.populateBuilderWithField(innerInputReader, builderSyncedRows, nestedFieldSyncedRows);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementSyncedRows(builderSyncedRows.build());
				}
				break;
			case fieldNumberConflictedRows:
				Vector vcConflictedRows = reader.readMessages(fieldNumberConflictedRows);
				for(int i = 0 ; i < vcConflictedRows.size(); i++) {
					byte[] eachBinData = (byte[]) vcConflictedRows.elementAt(i);
					DataRow.Builder builderConflictedRows = DataRow.newBuilder();
					InputReader innerInputReader = new InputReader(eachBinData, unknownTagHandler);
					boolean boolConflictedRows = true;
					int nestedFieldConflictedRows = -1;
					while(boolConflictedRows) {
						nestedFieldConflictedRows = getNextFieldNumber(innerInputReader);
						boolConflictedRows = DataRow.populateBuilderWithField(innerInputReader, builderConflictedRows, nestedFieldConflictedRows);
					}
					eachBinData = null;
					innerInputReader = null;
					builder.addElementConflictedRows(builderConflictedRows.build());
				}
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		SyncResponse.unknownTagHandler = unknownTagHandler;
	}

	public static SyncResponse parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static SyncResponse parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static SyncResponse parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}