/*******************************************************************************
 *    Copyright 2015 Dorian Perkins, Younghwan Go, Nitin Agrawal, Akshat Aranya
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *******************************************************************************/
package com.necla.simba.protocol;
// Generated by proto2javame, Sun Feb 08 14:12:26 KST 2015.

import java.io.IOException;
import java.io.InputStream;
import java.util.*;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.output.OutputWriter;
import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;

public final class UnsubscribeTable extends AbstractOutputWriter {
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	private final String app;
	private static final int fieldNumberApp = 1;

	private final String tbl;
	private static final int fieldNumberTbl = 2;


	public static Builder newBuilder() {
		return new Builder();
	}

	private UnsubscribeTable(final Builder builder) {
		if (builder.hasApp && builder.hasTbl ) {
			this.app = builder.app;
			this.tbl = builder.tbl;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " + 
				" app:" + builder.hasApp + " tbl:" + builder.hasTbl + "");
		}
	}

	public static class Builder {
		private String app;
		private boolean hasApp = false;

		private String tbl;
		private boolean hasTbl = false;


		private Builder() {
		}

		public Builder setApp(final String app) {
			this.app = app;
			this.hasApp = true;
			return this;
		}

		public Builder setTbl(final String tbl) {
			this.tbl = tbl;
			this.hasTbl = true;
			return this;
		}

		public UnsubscribeTable build() {
			return new UnsubscribeTable(this);
		}
	}

	public String getApp() {
		return app;
	}

	public String getTbl() {
		return tbl;
	}

	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "app = " + this.app + TAB;
		retValue += "tbl = " + this.tbl + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberApp, app);
		totalSize += ComputeSizeUtil.computeStringSize(fieldNumberTbl, tbl);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeString(fieldNumberApp, app);
		writer.writeString(fieldNumberTbl, tbl);
	}

	static UnsubscribeTable parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final UnsubscribeTable.Builder builder = UnsubscribeTable.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		switch (fieldNumber) {
			case fieldNumberApp:
				builder.setApp(reader.readString(fieldNumber));
				break;
			case fieldNumberTbl:
				builder.setTbl(reader.readString(fieldNumber));
				break;
		default:
			fieldFound = false;
		}
		return fieldFound;
	}

	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		UnsubscribeTable.unknownTagHandler = unknownTagHandler;
	}

	public static UnsubscribeTable parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	public static UnsubscribeTable parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	public static UnsubscribeTable parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}